version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSERNAME}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: marklive
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: